### ISSUE TITLE
daily cron job fails

### ISSUE THREAD

**Issue by promeneur** [sputnick-dev/cups2freefax#10]
voici le rapport envoyé par le système 

SCRIPT: cups2freefax.pl exited with RETURNCODE = 2.
SCRIPT: output (stdout && stderr) follows

cat: /root/.config/cups2freefax/cups2freefaxrc: No such file or directory
/etc/cron.daily/cups2freefax.pl: /root/.config/cups2freefax/docs.db: [No such file or directory]
SCRIPT: cups2freefax.pl
------- END OF OUTPUT

**Comment by promeneur** [comment]
après mise à jour voici un autre rapport d'erreur envoyé par le daemon cron

cat: /home/roubach/.config/cups2freefax/cups2freefaxrc: No such file or directory

**Comment by sputnick-dev** [comment]
C'est juste un warning, fixé avec 4d5a71eb113e68e3f73340c3e0695f2e458bdb33
