### ISSUE TITLE
Looking for the proper RUN file...

### ISSUE THREAD

**Issue by Spera06** [sputnick-dev/cups2freefax#2]
Bonjour,

je voulais réinstaller cette perle, mais le fameux "wget http://www.sputnick-area.net/scripts/cups2freefax/cups2freefax_current.run" ne trouve pas sa cible. Je sais que le projet est aussi hébergé ici mais le fameux .RUN n'y est pas présent. L'un d'entre vous aurait-il gardé le fichier ?

**Comment by sputnick-dev** [comment]
Bonjour, désolé pour la coupure, l'URL a changée :+1: 

```
wget http://sputnick.fr/scripts/cups2freefax/cups2freefax_current.run
```

**Comment by Spera06** [comment]
Bonjour, et merci pour la réponse rapide. Malheureusement, je reçois le message suivant:

--2014-01-30 10:32:30--  http://sputnick.fr/scripts/cups2freefax/cups2freefax_current.run
Résolution de sputnick.fr (sputnick.fr)... 2001:41d0:2:3d38::1, 94.23.60.56
Connexion vers sputnick.fr (sputnick.fr)|2001:41d0:2:3d38::1|:80... échec: Aucun chemin d'accès pour atteindre l'hôte cible.
Connexion vers sputnick.fr (sputnick.fr)|94.23.60.56|:80... connecté.
requête HTTP transmise, en attente de la réponse... 403 Forbidden
2014-01-30 10:32:40 ERREUR 403: Forbidden.

Vous serait-il possible de simplement m'envoyer le fichier par email ? Votre programme me manque tellement !

Date: Wed, 29 Jan 2014 15:13:09 -0800

**Comment by sputnick-dev** [comment]
Merci de re-essayer, je viens de tester, ça fonctionne (en ipv4)

**Comment by Spera06** [comment]
Merci, cela a finalement fonctionné !

Date: Thu, 30 Jan 2014 07:13:36 -0800
