### ISSUE TITLE
Unrecognized flag : -f

### ISSUE THREAD

**Issue by Vartkat** [sputnick-dev/cups2freefax#3]
Hello,

I was trying to install this on OS X. As I only would like the CLI I used the -f option...

Makeself doesn't seem to play nice with OS X.

Can you please provide us more detailed instructions about how this runs, and a manual install instructions.

For example, I see a PPD, which could be easily used on OS X for a printer install, but I don't know if this, used in conjunction with the config files, would be enough ?

Is this PPD a simple PDF converter or does it also send the file to Free ?

Of course, there's no Zenity on OS X, only bash, perl, and binaries would work. Is that enough to try to make it run on OS X ?

Thanks for your help

Regards

**Comment by sputnick-dev** [comment]
Do you have a specific error ?

Another way is to install the perl's prerequisites and use this script alone  https://raw.githubusercontent.com/sputnick-dev/cups2freefax/master/src/fax4free.pl  :  

```
./fax4free.pl -f file.pdf -d <phone number>
```

but you need a valid `cups2freefax` configuration, you can create it with (bash shell): 

``` bash
cat <<EOF > ~/.config/cups2freefax/cups2freefaxrc
# Fichier d'environnement de cups2freefax sourcé par cups2freefax.bash

# Login et password de l'interface free
login=<YOUR PHONE NUMBER>
password=<YOUR FREE PASSWORD>

# Masquer le numéro appelant : ( yes ou no. defaut = no )
cups2freefax_hide_fax_number=no

# Recevoir un rapport de transmission par e-mail : ( yes ou no. defaut =  no )
cups2freefax_email_confirmation=yes

# Durée en jours de rétention de la copie des faxs envoyés.
# Pour ne rien récuperer, mettre cups2freefax_faxs_store=0
cups2freefax_faxs_store=365

# Support de l'export DISPLAY en réseau
#cups2freefax_export_display=true
EOF
```

and edit the file to change `<YOUR PHONE NUMBER>` & `<YOUR FREE PASSWORD>`

**Comment by sputnick-dev** [comment]
Comment updated

**Comment by Vartkat** [comment]
OS X answer is 

Can't locate WWW/Mechanize.pm in @INC (@INC contains: /Library/Perl/5.16/darwin-thread-multi-2level /Library/Perl/5.16 /Network/Library/Perl/5.16/darwin-thread-multi-2level /Network/Library/Perl/5.16 /Library/Perl/Updates/5.16.2 /System/Library/Perl/5.16/darwin-thread-multi-2level /System/Library/Perl/5.16 /System/Library/Perl/Extras/5.16/darwin-thread-multi-2level /System/Library/Perl/Extras/5.16 .) at ./fax4free.pl line 29.
BEGIN failed--compilation aborted at ./fax4free.pl line 29.

I don't know what prerequisites you're talking of, seems to be the problem.

You didn't tell me if the PPD file is a simple PDF printer or something else. I'm dealing with html files which I convert to pdf using wkhtmltopdf.

Thanks for your help

Regards

**Comment by sputnick-dev** [comment]
Per'ls tell you that you have to install perl's module `WWW::Mechanize`.

The prerequisites are documented [here](https://github.com/sputnick-dev/cups2freefax/blob/master/README.md)

The PPD is yes a simple PDF printer, but you don't need it while you are using cli

**Comment by Vartkat** [comment]
OK, 

here is what I did :

1) install Cpan installation helper using instructions on 
http://triopter.com/archive/how-to-install-perl-modules-on-mac-os-x-in-4-easy-steps/

2) Install dependencies

$ sudo perl -MCPAN -e 'install WWW::Mechanize'
$ sudo perl -MCPAN -e 'install Net::SSLeay'
$ sudo perl -MCPAN -e 'install LWP::Protocol::https'

3) test to send a pdf
$ sudo ./fax4free.pl -f xxx.pdf -d 0123456789

The answer is 

"Le fax xxx.pdf a bien été envoyé vers 0123456789.

vous allez recevoir une confirmation via mail.

Use of uninitialized value $DISPLAY in concatenation (.) or string at ./fax4free.pl line 118.
Can't open perl script "/var/lib/cups2freefax/cron.pl": No such file or directory"

Do I really need $DISPLAY ?

I don't receive anything but this is not the fault of fax4free.pl cause it's the same using the OS X gui software FreeboxFax app.

Seems Free has changed something on their server side. I tried using their web interface and it's working. 
Can you try or your side and tell me your script is still working ?

Thanks for your precious help

**Comment by Vartkat** [comment]
OK, 

here is what I did :

1) install Cpan installation helper using instructions on 
http://triopter.com/archive/how-to-install-perl-modules-on-mac-os-x-in-4-easy-steps/

2) Install dependencies

$ sudo perl -MCPAN -e 'install WWW::Mechanize'
$ sudo perl -MCPAN -e 'install Net::SSLeay'
$ sudo perl -MCPAN -e 'install LWP::Protocol::https'

3) test to send a pdf
$ sudo ./fax4free.pl -f xxx.pdf -d 0123456789
The answer is 
Le fax xxx.pdf a bien été envoyé vers 0123456789.

vous allez recevoir une confirmation via mail.

Use of uninitialized value $DISPLAY in concatenation (.) or string at ./fax4free.pl line 118.
Can't open perl script "/var/lib/cups2freefax/cron.pl": No such file or directory

That's only for information purpose and to help others

**Comment by sputnick-dev** [comment]
I tried right now successfully.

The DISPLAY is not important, IIRC it's just a warning (I guess OsX don't use `DISPLAY` like linux).

Do you use the right fax number ? For a free **phone** number like 09 52 53 54 55 you should add 5 to the 4th number, so it becomes 09 57 53 54 55
