### ISSUE TITLE
Link not found at /usr/bin/fax4free line 103.

### ISSUE THREAD

**Issue by serpico** [sputnick-dev/cups2freefax#4]
Hi,
Tried to use the CLI tool with xubuntu 16.04

`fax4free -d 0176xxxxx -f /home/arno/liste.pdf`

return

`Link not found at /usr/bin/fax4free line 103.`

Could it be a thing with how the menus are displayed these days ?

Thanks

**Comment by sputnick-dev** [comment]
Bonjour, free étant un service francais, je parles en francais ;)

Effectivement, la page a changée, je viens de commiter des changements.

Merci pour le retour

**Comment by serpico** [comment]
Merci pour les modifs.
;) ça fonctionne.

Pour info, juste après le message de confirmation d'envoi :
`printout("Le fax $Doc2Fax a bien été envoyé vers $destinataire.\n");`

`sh: 1: source: not found`
`sh: 4: Syntax error: "&" unexpected`
est affiché

**Comment by sputnick-dev** [comment]
Re-installe ou applique le dernier commit, ca devrait fonctionner...
