### ISSUE TITLE
envoyer un fax échoue dès les premières étapes

### ISSUE THREAD

**Issue by promeneur** [sputnick-dev/cups2freefax#7]
openSuse 42.3
kde apps 17.12.2
plasma 5.12.2
kde framework 5.43

après l'installation, j'ouvre un fichier texte
puis
J'imprime sur cups2freefax
puis
rien ne se passe, pas d'icône dans le systray, pas de fenêtre de dialogue

1. contenu de ~/config/cups2freefax/log/cups2freefax.log

lun. mars  5 11:25:46 CET 2018
On traite /var/spool/cups2freefax/roubach/reponse_prise_optique.pdf pour roubach...
No protocol specified
No protocol specified
Unable to init server: Impossible de se connecter : Connexion refusée

(zenity:4684): Gtk-WARNING **: cannot open display: :0

pour cette dernière erreur je l'ai déjà rencontrée avec une application voulant afficher une icône dans le systray la solution a été de remplacer

env DISPLAY=:0 /usr/bin/luckybackup --silent --skip-critical /home/roubach/.luckyBackup/profiles/default.profile > /home/roubach/.luckyBackup/logs/default-LastCronLog.log 2>&1

par

env DISPLAY=:0 XAUTHORITY=/tmp/xauth-1000-_0 /usr/bin/luckybackup --silent --skip-critical /home/roubach/.luckyBackup/profiles/default.profile > /home/roubach/.luckyBackup/logs/default-LastCronLog.log 2>&1

2. contenu de /var/log/cups/cup2freefax.log

Mon Mar  5 11:09:19 2018  [STATUS] directory created (/var/spool/cups2freefax)
Mon Mar  5 11:09:19 2018  [STATUS] directory created (/var/spool/cups2freefax/SPOOL)
Mon Mar  5 11:09:19 2018  [STATUS] spool directory created (/var/spool/cups2freefax/SPOOL)
Mon Mar  5 11:09:19 2018  [STATUS] identification string sent
Mon Mar  5 11:12:15 2018  [STATUS] identification string sent
Mon Mar  5 11:13:58 2018  [STATUS] directory created (/var/spool/cups2freefax/roubach)
Mon Mar  5 11:14:00 2018  [STATUS] PDF creation successfully finished (roubach)
Mon Mar  5 11:17:19 2018  [STATUS] directory created (/var/spool/cups2freefax/root)
Mon Mar  5 11:17:19 2018  [STATUS] PDF creation successfully finished (root)
Mon Mar  5 11:25:47 2018  [STATUS] PDF creation successfully finished (roubach)
Mon Mar  5 11:28:09 2018  [STATUS] identification string sent

3. contenu de /var/log/cups/error.log

W [05/Mar/2018:09:15:54 +0100] CreateProfile failed: org.freedesktop.DBus.Error.ServiceUnknown:The name org.freedesktop.ColorManager was not provided by any .service files
W [05/Mar/2018:09:15:54 +0100] CreateDevice failed: org.freedesktop.DBus.Error.ServiceUnknown:The name org.freedesktop.ColorManager was not provided by any .service files
W [05/Mar/2018:11:00:53 +0100] CreateProfile failed: org.freedesktop.DBus.Error.ServiceUnknown:The name org.freedesktop.ColorManager was not provided by any .service files
W [05/Mar/2018:11:00:53 +0100] CreateProfile failed: org.freedesktop.DBus.Error.ServiceUnknown:The name org.freedesktop.ColorManager was not provided by any .service files
W [05/Mar/2018:11:00:53 +0100] CreateDevice failed: org.freedesktop.DBus.Error.ServiceUnknown:The name org.freedesktop.ColorManager was not provided by any .service files
E [05/Mar/2018:11:09:26 +0100] [cups-driverd] Bad driver information file "/usr/share/cups/drv/sample.drv"!
E [05/Mar/2018:11:09:26 +0100] [cups-driverd] Bad driver information file "/usr/share/cups/drv/cupsfilters.drv"!
E [05/Mar/2018:11:09:26 +0100] [cups-driverd] Bad driver information file "/usr/share/cups/drv/generic-brf.drv"!
E [05/Mar/2018:11:09:26 +0100] [cups-driverd] Bad driver information file "/usr/share/cups/drv/indexv3.drv"!
E [05/Mar/2018:11:09:26 +0100] [cups-driverd] Bad driver information file "/usr/share/cups/drv/indexv4.drv"!
E [05/Mar/2018:11:12:20 +0100] [cups-driverd] Bad driver information file "/usr/share/cups/drv/sample.drv"!
E [05/Mar/2018:11:12:20 +0100] [cups-driverd] Bad driver information file "/usr/share/cups/drv/cupsfilters.drv"!
E [05/Mar/2018:11:12:20 +0100] [cups-driverd] Bad driver information file "/usr/share/cups/drv/generic-brf.drv"!
E [05/Mar/2018:11:12:20 +0100] [cups-driverd] Bad driver information file "/usr/share/cups/drv/indexv3.drv"!
E [05/Mar/2018:11:12:20 +0100] [cups-driverd] Bad driver information file "/usr/share/cups/drv/indexv4.drv"!
W [05/Mar/2018:11:13:10 +0100] CreateProfile failed: org.freedesktop.DBus.Error.ServiceUnknown:The name org.freedesktop.ColorManager was not provided by any .service files
W [05/Mar/2018:11:13:10 +0100] CreateProfile failed: org.freedesktop.DBus.Error.ServiceUnknown:The name org.freedesktop.ColorManager was not provided by any .service files
W [05/Mar/2018:11:13:10 +0100] CreateDevice failed: org.freedesktop.DBus.Error.ServiceUnknown:The name org.freedesktop.ColorManager was not provided by any .service files
W [05/Mar/2018:11:22:20 +0100] CreateProfile failed: org.freedesktop.DBus.Error.ServiceUnknown:The name org.freedesktop.ColorManager was not provided by any .service files
W [05/Mar/2018:11:22:20 +0100] CreateProfile failed: org.freedesktop.DBus.Error.ServiceUnknown:The name org.freedesktop.ColorManager was not provided by any .service files
W [05/Mar/2018:11:22:20 +0100] CreateDevice failed: org.freedesktop.DBus.Error.ServiceUnknown:The name org.freedesktop.ColorManager was not provided by any .service files
W [05/Mar/2018:11:22:20 +0100] CreateProfile failed: org.freedesktop.DBus.Error.ServiceUnknown:The name org.freedesktop.ColorManager was not provided by any .service files
W [05/Mar/2018:11:22:20 +0100] CreateDevice failed: org.freedesktop.DBus.Error.ServiceUnknown:The name org.freedesktop.ColorManager was not provided by any .service files
E [05/Mar/2018:11:28:13 +0100] [cups-driverd] Bad driver information file "/usr/share/cups/drv/sample.drv"!
E [05/Mar/2018:11:28:13 +0100] [cups-driverd] Bad driver information file "/usr/share/cups/drv/cupsfilters.drv"!
E [05/Mar/2018:11:28:13 +0100] [cups-driverd] Bad driver information file "/usr/share/cups/drv/generic-brf.drv"!
E [05/Mar/2018:11:28:13 +0100] [cups-driverd] Bad driver information file "/usr/share/cups/drv/indexv3.drv"!
E [05/Mar/2018:11:28:13 +0100] [cups-driverd] Bad driver information file "/usr/share/cups/drv/indexv4.drv"!

4. contenu de /var/log/cups/page.log

HP_LaserJet_1220 roubach 1 [11/Oct/2017:19:43:48 +0200] 1 1 - localhost hbf-0110196242-e_1Jsnqa.pdf - -
CUPS2FREEFAX roubach 8 [05/Mar/2018:11:13:58 +0100] 1 1  localhost reponse_prise_optique.txt A4 one-sided
CUPS2FREEFAX root 9 [05/Mar/2018:11:17:19 +0100] 1 1 - localhost YaST2testprint_CUPS2FREEFAX - -
CUPS2FREEFAX roubach 10 [05/Mar/2018:11:25:45 +0100] 1 1  localhost reponse_prise_optique.txt A4 one-sided

5. le fichier cups2freefax.pl est curieusement dans /etc/cron.daily !

**Comment by sputnick-dev** [comment]
On dirait que tu a utilisé une version obsolete.

Peut tu cloner le repository, puis : 

```
$ sudo ./start -u # uninstall
$ sudo ./start 
```

Dans `/etc/cron.daily/` c'est normal, c'est pour récupérer les PDF qui sont sur la page de free.

**Comment by promeneur** [comment]
j'ai cloné avec la commande dans le rmd.
git clone https://github.com/sputnick-dev/cups2freefax.git

si ancienne version alors elle est dans le dépôt git. non ?

**Comment by promeneur** [comment]
en ce qui concerne cups2freefax.pl dans cron.daily
voici le rapport d'erreur envoyé sous forme de courrier.

SCRIPT: cups2freefax.pl exited with RETURNCODE = 2.
SCRIPT: output (stdout && stderr) follows

cat: /root/.config/cups2freefax/cups2freefaxrc: No such file or directory
/etc/cron.daily/cups2freefax.pl: /root/.config/cups2freefax/docs.db: [No such file or directory]
SCRIPT: cups2freefax.pl

**Comment by sputnick-dev** [comment]
Ces problèmes sont normalement fixés avec les nouveaux commits.

Concernant `/etc/cron.daily` ça sert à être sur de récupérer les faxs transmis dans `~/.config/cups2freefax/envoyes/`

**Comment by promeneur** [comment]
le fax n'est toujours pas envoyé.

quand on imprime avec cups2freefax
alors
l’icône d'imprimante apparaît brièvement et c'est tout.

1. contenu de ~/config/cups2freefax/log/cups2freefax.log

mar. mars  6 09:26:10 CET 2018
On traite /var/spool/cups2freefax/roubach/reponse_prise_optique.pdf pour roubach...
No protocol specified
No protocol specified
Unable to init server: Impossible de se connecter : Connexion refusée

(zenity:9301): Gtk-WARNING **: cannot open display: :0
+ [[ -n '' ]]
+ set +x
'/var/spool/cups2freefax/roubach/reponse_prise_optique.pdf' supprimé

2. contenu de /var/log/cups/cup2freefax.log

Tue Mar  6 09:26:11 2018  [STATUS] PDF creation successfully finished (roubach)

3. contenu de /var/log/cups/error.log

rien concernant cups2freefax

4. /var/log/cups/page.log

CUPS2FREEFAX roubach 13 [06/Mar/2018:09:26:10 +0100] 1 1  localhost reponse_prise_optique.txt A4 one-sided

5. /var/log/cups/access.log

localhost - - [06/Mar/2018:00:20:52 +0100] "POST / HTTP/1.1" 200 155 Cancel-Subscription successful-ok
localhost - - [06/Mar/2018:00:20:52 +0100] "POST / HTTP/1.1" 200 417 Create-Printer-Subscriptions successful-ok
localhost - - [06/Mar/2018:00:20:52 +0100] "POST / HTTP/1.1" 200 155 Cancel-Subscription successful-ok
localhost - - [06/Mar/2018:08:19:02 +0100] "POST / HTTP/1.1" 200 417 Create-Printer-Subscriptions successful-ok
localhost - - [06/Mar/2018:09:17:22 +0100] "POST / HTTP/1.1" 200 186 Renew-Subscription successful-ok
localhost - - [06/Mar/2018:09:26:10 +0100] "POST /printers/CUPS2FREEFAX HTTP/1.1" 200 342 Create-Job successful-ok
localhost - - [06/Mar/2018:09:26:10 +0100] "POST /printers/CUPS2FREEFAX HTTP/1.1" 200 20602 Send-Document successful-ok
localhost - - [06/Mar/2018:09:26:20 +0100] "POST / HTTP/1.1" 200 155 Cancel-Subscription successful-ok
localhost - - [06/Mar/2018:09:26:20 +0100] "POST / HTTP/1.1" 200 565 Create-Printer-Subscriptions successful-ok
localhost - - [06/Mar/2018:09:26:24 +0100] "POST / HTTP/1.1" 200 417 Create-Printer-Subscriptions successful-ok
localhost - - [06/Mar/2018:09:26:24 +0100] "POST / HTTP/1.1" 200 155 Cancel-Subscription successful-ok
localhost - - [06/Mar/2018:09:26:24 +0100] "POST / HTTP/1.1" 200 547 Create-Printer-Subscriptions successful-ok
localhost - - [06/Mar/2018:09:26:26 +0100] "POST / HTTP/1.1" 200 155 Cancel-Subscription successful-ok
localhost - - [06/Mar/2018:09:26:26 +0100] "POST / HTTP/1.1" 200 359 Create-Printer-Subscriptions successful-ok
localhost - - [06/Mar/2018:09:26:26 +0100] "POST / HTTP/1.1" 200 155 Cancel-Subscription successful-ok

**Comment by promeneur** [comment]
est-il normal que le pilote soit "generic postscript printer" et non pas CUPS2FREEFAX.ppd ?

**Comment by sputnick-dev** [comment]
Si tu a autre chose que ça dans le repository
```
$ git log | head -1
commit eb17332ef679050bdcf7130d998049444761fbdd
```

l faut faire : 
```
$ git pull
$ sudo ./start
````

Le PPD est normal, oui

**Comment by promeneur** [comment]
j'ai téléchrgé ce matin à 9 h 45

**Comment by promeneur** [comment]
@linux-58nc:~/rpmd/free/cups2freefax/cups2freefax> git log | head -1
commit eb17332ef679050bdcf7130d998049444761fbdd

**Comment by promeneur** [comment]
l'outil yast me dit qu'aucune imprimante n'est connectée.
mon imprimante hp est éteinte donc normal mais l'imprimante cups2freefax devrait être connectée en permanence et je ne devrai pas avoir une telle info de la part de yast. non ?
